version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 4000:4000
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rrobles
      - MYSQL_DB=pruebainfodesign
    links:
      - db
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: pruebainfodesign
      MYSQL_ROOT_PASSWORD: rrobles
    volumes:
      - ./backend/pruebainfodesign.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
